--- #YAML:1.0
name: Parse-BACKPAN-Packages
version: 0.32
author:
  - Leon Brocard <acme@astray.com>
abstract: Provide an index of BACKPAN
license: perl
generated_by: Module::Build version 0.2611, without YAML.pm
